# Generated by Django 5.0.4 on 2024-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_background_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='background_img',
            field=models.ImageField(default='4.png', height_field=500, upload_to='backgrounds/', width_field=500),
        ),
    ]
