# Generated by Django 5.0.4 on 2025-04-05 23:10

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_background_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=users.models.user_directory_path),
        ),
    ]
