"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from django.apps import AppConfig
import environ

from dotenv import load_dotenv
env = environ.Env()
environ.Env.read_env()
HUGGINGFACE_TOKEN = env('HUGGINGFACE_TOKEN')
DEEPSEEK_API_KEY=env('DeepSeek')
GOOGLE_API_KEY=env('GOOGLE_API_KEY')
load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_BEAT_SCHEDULE ={
#     'send_email_task':{
#         'task':
#             'messages_main.tasks.send_email_tasks',
#         'shedule':
#             timedelta(minutes=5),
#         'args': (
#             'Subject',
#             'Message',
#             [
#                 'recipient@example.com'
#             ]
#         )
#     },
# }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AppConfig.default = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tvgtjsw%d+skrljq$slxt7u(a_x1*3qp0$(6!b2k(v!bnct(8&'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = [ '93.120.189.147','192.168.0.161','localhost',]

STATIC_URL = '/static/'
if DEBUG:
    STATIC_DIR = os.path.join(BASE_DIR, 'static')
    STATICFILES_DIRS = [
        STATIC_DIR,
        '/var/www/static/',
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
    STATICFILES_FINDERS = (
        'django.contrib.staticfiles.finders.FileSystemFinder',
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    )
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # или другой механизм сессий
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 3600  # Время жизни сессии в секундах (1 час)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Не выходить при закрытии браузера



SITE_ID = 1
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'API',
    'csp',
    'NeuraChatBot',
    'messages_main',
    'users',
    'django_forms_bootstrap',
    'bootstrap3',
    'groups',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'messages_main.middleware.LinkBlockerMiddleware',
    'groups.middleware.LinkBlockerMiddleware',
    'messages_main.middleware.WordsBlockerMiddleware',
    'csp.middleware.CSPMiddleware',
    'main.middleware.RestrictAdminMiddleware',

]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'main_page.context_processors.song_list',
                'main_page.context_processors.chat_messages',
                'users.context_processors.friends_list',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

ASGI_APPLICATION = 'main.wsgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('93.120.189.147', 8085)],
        },
    },
}
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'sign/login/'
LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL='auth.User'
CSRF_TRUSTED_ORIGINS = [
    'http://93.120.189.147:8085',
    'https://93.120.189.147:8085',
    
    ]
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    'https://code.jquery.com/',
    'http://gc.kis.v2.scr.kaspersky-labs.com',
    'ws://gc.kis.v2.scr.kaspersky-labs.com',
    'http://93.120.189.147:8085/static/js/main.js',
    'http://93.120.189.147:8085/static/js/messages.js',
    "'nonce-HelloFromHell5156'", 
    
    # Добавление nonce для встроенных скриптов
)
CSP_STYLE_SRC = ("'self'", 'https://trusted.cdn.com', "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", 'data:', 'https://trusted.cdn.com'
               ,'https://icons.iconarchive.com/icons/johanchalibert/mac-osx-yosemite/1024/messages-icon.png',
               'https://avatars.mds.yandex.net/i?id=3686d64639e9d6abc607b5be43314f4614ffcd6b-10844270-images-thumbs&n=13',
               'https://avatars.mds.yandex.net/i?id=be10b347d5003d7ff3813ab7fcdd22a70a7dca49-12399165-images-thumbs&n=13',
               )
CSP_FONT_SRC = ("'self'", 'https://trusted.cdn.com')
CSP_CONNECT_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)
CSP_FRAME_SRC = ("'none'",)
CSP_MEDIA_SRC = ("'self'",)

