# Generated by Django 4.1 on 2024-02-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groups_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforgroups',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/GroupsPosts'),
        ),
    ]
