# Generated by Django 4.1 on 2024-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_postmessages_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforgroups',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
