# Generated by Django 5.0.4 on 2025-02-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_main', '0020_alter_message_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['type']},
        ),
    ]
