# Generated by Django 5.0.4 on 2025-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_main', '0021_alter_chat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('black', 'black'), ('white', 'white')], default='#f9f9f9', max_length=6),
        ),
    ]
