# Generated by Django 5.0.4 on 2025-03-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_main', '0022_alter_message_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pub_date']},
        ),
    ]
