# Generated by Django 5.0.4 on 2025-03-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_main', '0023_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['type', 'message_in_chat']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='chat',
            name='message_in_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message_in_chats', to='messages_main.message'),
        ),
    ]
