# Generated by Django 5.0.4 on 2025-03-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_main', '0027_alter_chat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_in_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message_in_chat', to='messages_main.message'),
        ),
    ]
