# Generated by Django 5.0.4 on 2025-04-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_main', '0030_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
    ]
