# Generated by Django 5.0.4 on 2024-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('NotFriends', 'Not a friends'), ('WaitingRequest', 'Waiting a request'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Waiting a request', max_length=25),
        ),
    ]
