# Generated by Django 4.1 on 2024-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_postforgroups_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforgroups',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
