# Generated by Django 4.1 on 2024-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_postmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessages',
            name='contentForPosts',
            field=models.TextField(default=''),
        ),
    ]
