# Generated by Django 4.1 on 2024-03-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_postmessages_contentforposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessages',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='groups.postforgroups'),
        ),
    ]
