# Generated by Django 4.1 on 2024-03-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_postmessages_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessages',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='groups.postforgroups'),
        ),
    ]
