# Generated by Django 5.0.4 on 2024-05-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_alter_groups_adminforgroups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='AdminForGroups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groups',
            name='images',
            field=models.ImageField(default='/media/backgrounds/ForNothing.jpg', upload_to='media/GroupsImages'),
        ),
    ]
