# Generated by Django 5.0.4 on 2025-02-26 12:27

import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_alter_groups_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='images',
            field=models.ImageField(default='media/backgrounds/ForNothing.jpg', upload_to=groups.models.Group_directory_path),
        ),
    ]
