# Generated by Django 5.0.4 on 2025-03-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_alter_groups_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postforgroups',
            options={'ordering': ['time_create']},
        ),
        migrations.AlterModelOptions(
            name='postmessages',
            options={'ordering': ['pub_date']},
        ),
    ]
