# Generated by Django 5.0.4 on 2025-03-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_alter_postforgroups_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['name']},
        ),
    ]
